# Usar una imagen base de OpenJDK
FROM openjdk:17-jdk-alpine

# Establecer el directorio de trabajo en el contenedor
WORKDIR /appTest

# Copiar el archivo JAR generado al contenedor
COPY target/technicalExercise-0.0.1-SNAPSHOT.jar /appTest/technicalExercise.jar

# Exponer el puerto en el que se ejecutará la aplicación
EXPOSE 8080

# Comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "technicalExercise.jar"]