version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-xe:latest
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=1234
      - ORACLE_DATABASE=TechnicalTest
      - ORACLE_USER=SYSTEM
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data: